### ISSUE TITLE
User Story: Authentification only when needed

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/ProjectBoard#61]
As a user I don't want to authenticate for a public repo / project board in order to minimize the amount of data I have to provide.

**Comment by SaturnHafen** [comment]
Hi!

We currently don't know to which extend the query-api is available without authentication, but due to rate-limiting, using the api unauthenticated will not be very pleasant (you are only allowed to make 60 Requests per hour, which is probably to little to fetch [this board](https://github.com/hpi-swa-teaching/ProjectBoard/projects/1)).

On top, Squello currently does not support read-only project boards (which is *not* a small feature) which would be required, because you can not make any changes to a board without signing in. Because of that, this story will not be implemented in this iteration.
